#!/usr/bin/env bash
#Script that install and configure nginx web server.

sudo apt-get update
sudo apt-get install -y nginx
sudo echo "Hello World!" > /var/www/html/index.bginx.debian.html
sudo service nginx start
