#!/usr/bin/env bash
#Script that install and configure nginx web server.
apt-get -y update
apt-get -y install nginx
sed -i 's/8000/80/g' /etc/nginx/sites-enabled/default
#echo "Hello World!" > /var/www/html/index.nginx-debian.html
service nginx start
