#!/usr/bin/env bash
#Script that install and configure nginx web server.
apt-get -y update
apt-get -y install nginx
sed -i 's/8000/80/g' /etc/nginx/sites-enabled/default
echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/twitter.com\/Abd0_3mg;\n\n\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}/" /etc/nginx/sites-available/default
sudo /etc/init.d/nginx restart
sudo service nginx start
