#!/usr/bin/env bash
#Script that configures th HAPROXY.

apt-get -y update
apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.8
apt-get -y install haproxy=2.8.\*
echo -e "\nfrontend haproxy\n\tbind *:80\n\tmode http\n\tdefault_backend ser\n\nbackend ser\n\tbalance roundrobin\n\tserver $HOSTNAME 18.209.179.152:80 check\n\tserver $HOSTNAME 3.86.13.133:80 check\n" >> /etc/haproxy/haproxy.cfg
service haproxy restart
