#!/usr/bin/env bash
#This script tells ftory about the passwd file.
while IFS=':' read -r usern passw uid gid inf home shell; do
  echo "The user $usern is part of the $gid gang,"\
  "lives in $home and rides $shell."\
  "$uid's place is protected by the passcode $passw,"\
  "more info about the user here: $inf"
done < "/etc/passwd"

